### ISSUE TITLE
Specifying ports createContainerAsync

### ISSUE THREAD

**Issue by Jipperism** [Microsoft/Docker.DotNet#134]
I can't figure out how to correctly create a container listening to the correct ports. ```CreateContainerParameters.ExposedPorts``` is defined as a ```Dictionary<string, object>``` but using the docker remote api specification I cant figure out what input to pass in here (the ```object``` part that is).

**Output of `dotnet --info`:**

```
Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**What version of Docker.DotNet?:**

```
"Docker.DotNet": "2.124.3"
```

**Steps to reproduce the issue:**
1. Call createContainersAsync.
2. input null or any other object as ```CreateContainerParameters.ExposedPorts```.

**What actually happened?:**
Docker is not listening to the correct port. ```docker ps``` shows ```5432/tcp``` instead of ```0:0:0:0:5432->5432/tcp```.

**What did you expect to happen?:**
```0:0:0:0:5432->5432/tcp```.

**Additional information:**

**Comment by Jipperism** [comment]
Hi daniel,

I solved it in the following manner:

```
var exposedPorts = new Dictionary<string, object> {
    { containerPort, new { HostPort = portNo } }
};
```

I hope this helps you.

**Comment by AndrewBennet** [comment]
Just chiming in here as I had this problem and found I also needed to set the HostConfig.PortBindings property. The full block I ended up using looks like:

    string mContainerPort = "8080";
    string mHostPort = "8081";

    CreateContainerParameters createParameters = new CreateContainerParameters {
        // Image, Name, Entrypoint, ...
        ExposedPorts = new Dictionary<string, object> {
            {
                mContainerPort, new {
                    HostPort = mHostPort
                }
            }
        },
        HostConfig = new HostConfig {
            PortBindings = new Dictionary<string, IList<PortBinding>> {
                {
                    mContainerPort, new List<PortBinding> {
                        new PortBinding {
                            HostPort = mHostPort
                        }
                    }
                }
            }
        }
    }

**Comment by karldodd** [comment]
I met the same issue here. I was trying to start a sqlserver container in C#:

```
docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=mypassword" -a stdin -a stdout -a stderr -p 1433:1433 microsoft/mssql-server-linux
```

My code looks like ( as @AndrewBennet  suggested)

```C#
        [AssemblyInitialize]
        public static void BootSqlServerOnLinuxWithDocker(TestContext tc)
        {
            DockerClient client = new DockerClientConfiguration(new Uri("npipe://./pipe/docker_engine")).CreateClient();
            var response = client.Containers.CreateContainerAsync(new CreateContainerParameters {
                Image = "microsoft/mssql-server-linux",
                AttachStderr = true,
                AttachStdin = true,
                AttachStdout = true,
                Env = new[] { "ACCEPT_EULA=Y", $"SA_PASSWORD={s_saPassword}" },
                ExposedPorts = new Dictionary<string, object>() {
                    { 1433.ToString(), new { HostPort = 1433.ToString() } }
                },
                HostConfig = new HostConfig
                {
                    PortBindings = new Dictionary<string, IList<PortBinding>> {
                        {
                            1433.ToString(), new List<PortBinding> {
                                new PortBinding { HostPort = 1433.ToString() }
                            }
                        }
                    }
                }

            }).Result;
            s_runningSqlServerContainerID = response.ID;
            client.Containers.StartContainerAsync(s_runningSqlServerContainerID, new ContainerStartParameters { }).Wait();
        }
```

How I constructed connection string:

```C#
            SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();
            builder.DataSource = "localhost";   // update me
            builder.UserID = "sa";              // update me
            builder.Password = "somepassword";
            builder.InitialCatalog = "somedb";
            return builder.ConnectionString;
```

The error I got:

```
System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.) ---> System.ComponentModel.Win32Exception: An existing connection was forcibly closed by the remote host

Result StackTrace:	
at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
```

The connection **can be successfully opened by using the docker command line mentioned above**, but fails when using Docker.DotNet. So my sql connection test code should be fine.

Do I miss anything when using using Docker.DotNet? Thanks.

**Comment by jterry75** [comment]
What does `docker inspect <containerid>` return after your call to CreateContainerAsync? Does it show the port bindings are setup properly? Is possible there is something wrong with the schema for the version of docker daemon you are using.

**Comment by villainoustourist** [comment]
@karldodd - this issue is common when the SQL container is under memory pressure.  Try giving it more memory (or to the docker host or mobylinux VM if you're running on Windows).
