### ISSUE TITLE
StartContainerExecAsync fails with DockerContainerNotFoundException

### ISSUE THREAD

**Issue by marcuslindblom** [Microsoft/Docker.DotNet#215]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4
```

**What version of Docker.DotNet?:**

```
2.124.3
```

**Steps to reproduce the issue:**
1. sudo docker ps -a
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                           PORTS                                              NAMES
25b933366a88        jrottenberg/ffmpeg              "ffmpeg -i https:/..."   34 minutes ago      Exited (0) 34 minutes ago                                                           wonderful_cray
25c05dbf7e65        ravendb/ravendb:ubuntu-latest   "/bin/sh -c /opt/r..."   42 minutes ago      Up 42 minutes                    0.0.0.0:8080->8080/tcp, 0.0.0.0:38888->38888/tcp   quizzical_poincare
2e04b598816d        ravendb/ravendb:ubuntu-latest   "/bin/sh -c /opt/r..."   About an hour ago   Exited (137) 45 minutes ago                                                         mystifying_lalande
89aecfa6122f        ravendb/ravendb:ubuntu-latest   "/bin/sh -c /opt/r..."   About an hour ago   Exited (137) About an hour ago                                                      hopeful_bardeen
9d650c177226        ravendb/ravendb:ubuntu-latest   "/bin/sh -c /opt/r..."   About an hour ago   Exited (255) About an hour ago   0.0.0.0:8080->8080/tcp, 0.0.0.0:38888->38888/tcp   eloquent_minsky
2906902d11a5        ravendb/ravendb:ubuntu-latest   "/bin/sh -c /opt/r..."   3 hours ago         Exited (137) About an hour ago                                                      brave_volhard
bc4f15e3cbc4        ravendb/ravendb:ubuntu-latest   "/bin/sh -c /opt/r..."   3 hours ago         Exited (137) 3 hours ago                                                            nervous_almeida
```
2. grab first id of container
3. run the following code
```c#
  const string id = "25b933366a88";
  var client = new DockerClientConfiguration(new Uri("unix:///var/run/docker.sock")).CreateClient();
  await client.Containers.StartContainerExecAsync(id, default(CancellationToken));
```

**What actually happened?:**
Got exception:

```
Docker.DotNet.DockerContainerNotFoundException: Docker API responded with status code=NotFound, response={"message":"No such exec instance '25b933366a88' found in daemon"}

   at Docker.DotNet.ContainerOperations.<>c.<.cctor>b__29_0(HttpStatusCode statusCode, String responseBody)
   at Docker.DotNet.DockerClient.HandleIfErrorResponse(HttpStatusCode statusCode, String responseBody, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.<MakeRequestAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Aperture.Controllers.HomeController.<Index>d__5.MoveNext() in /home/maqe/Projects/aperture/src/Controllers/HomeController.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**What did you expect to happen?:**
I expected the container to be started.

**Additional information:**

**Comment by swernli** [comment]
This is expected.  The method you are calling is for starting an exec instance that has already been created, so it expects an exec ID not a container ID (which is why the error from the daemon is "No such exec instance").  If your intent is to start a process inside of a container, you need to start with `ExecCreateContainerAsync` on a running container.  If you are just trying to start a container, the method you are looking for is `StartContainerAsync`.  For reference, see the docker engine remote API documented here: https://docs.docker.com/engine/api/v1.24/.  Since Docker.DotNet is designed to wrap this engine API, the endpoints and objects match this documentation more than what folks are used to from the docker CLI.

**Comment by marcuslindblom** [comment]
@swernli Ok. I'm trying to run do a `docker run` with some additional parameters.

If I understand correctly from the documentation I need to create the container, start the container and then attach to the container. I also need to add some additional parameters to the run command. I think this is done by passing `CreateContainerParameters(config)` to the `CreateContainerAsync` method like this:

```c#
var parameters = new Config {
  Image = "d5db001b2b8a",              
  ArgsEscaped = true,
  AttachStderr = true,
  AttachStdin = true,
  AttachStdout = true,              
  Cmd = new string[] { " -i http://foobar.com -c:a copy -f mjpeg -preset ultrafast -an -c:v mjpeg -vf \"select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50\" -q:v 20 -vframes 1 pipe:1" }
};

CreateContainerResponse response = await client.Containers.CreateContainerAsync(new CreateContainerParameters(parameters));
```

When the container is created I start and attach to it like this:

```c#
Task task = client.Containers.StartContainerAsync(response.ID, new ContainerStartParameters());

var config = new ContainerAttachParameters {
  Stream = true,
  Stderr = true,
  Stdin = false,
  Stdout = true,
  Logs = "1"
};   

var buffer = new byte[1024];
using (var stream = await client.Containers.AttachContainerAsync(response.ID, false, config, default(CancellationToken)))
{
    var result = await stream.ReadOutputAsync(buffer, 0, buffer.Length, default(CancellationToken));
    do
    {
        Console.Write(Encoding.UTF8.GetString(buffer, 0, result.Count));
    }
    while (!result.EOF);
}
```

The container seems to start by the `Cmd` does not run, probably because it's not the correct way of adding additional parameters to the `run` command?

The complete command I'm trying to run using the remote API is this: `docker run jrottenberg/ffmpeg -i http://foobar.com -c:a copy -f mjpeg -preset ultrafast -an -c:v mjpeg -vf "select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50" -q:v 20 -vframes 1 - > scrub.jpg`

Have I missed something obvious?
