### ISSUE TITLE
Requesting new docker client release

### ISSUE THREAD

**Issue by mrohera** [Microsoft/Docker.DotNet#304]
**Output of `dotnet --info`:**

```
$ docker --version
Docker version 18.03.0-ce, build 0520e24 

$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview3-008427
 Commit:    423010bf0d

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x86
 Base Path:   /home/moxa/tools/dotnet/2.1.300-preview3-008427_patch/sdk/2.1.300-preview3-008427/

Host (useful for support):
  Version: 2.1.0-preview3-26330-04
  Commit:  65157f4408

.NET Core SDKs installed:
  2.1.300-preview3-008427 [/home/moxa/tools/dotnet/2.1.300-preview3-008427_patch/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.0-preview3-26330-04 [/home/moxa/tools/dotnet/2.1.300-preview3-008427_patch/shared/Microsoft.NETCore.App]

```

**What version of Docker.DotNet?:**

```
3.125.0
```

**Steps to reproduce the issue:**
```
<snip>
            const string UriString = @"unix:///var/run/docker.sock";
            DockerClient client = new DockerClientConfiguration(new Uri(UriString))
                .CreateClient();
            var info = client.System.GetSystemInfoAsync().Result;
```

**What actually happened?:**
```
Docker.DotNet.DockerApiException: Docker API responded with status code=BadRequest, response=400 Bad Request: unsupported protocol version
   at Docker.DotNet.DockerClient.HandleIfErrorResponse(HttpStatusCode statusCode, String responseBody, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.SystemOperations.GetSystemInfoAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironment.CreateAsync(IDockerClient client, IEntityStore`2 store, IRestartPolicyManager restartManager) in /mnt/d/src/Azure-IoT-Edge-Core/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironment.cs:line 49
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule.<>c.<<Load>b__10_8>d.MoveNext() in /mnt/d/src/Azure-IoT-Edge-Core/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule.<>c.<<Load>b__10_12>d.MoveNext() in /mnt/d/src/Azure-IoT-Edge-Core/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /mnt/d/src/Azure-IoT-Edge-Core/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 160
```
**What did you expect to happen?:**
Obtain the docker info details.

**Additional information:**
In experimenting on ARM devices and Dot Net Core 2.1.0 runtime we ran into this exception.

When building the latest code in master we found breaking changes and so we took a shortcut and integrated just the changes in  [https://github.com/Microsoft/Docker.DotNet/pull/299](https://github.com/Microsoft/Docker.DotNet/pull/299) over 3.125.0 and we did not see this issue.

**So the ask is the following:**
- Are you planning to make a 3.125.x or some 3.x release in the future? If so we would need the fix in the PR mentioned above. Also if possible please indicate an ETA, this would be helpful for scheduling purposes.
- Or are you planning a release based on a snapshot of master? If so please let us know by when this can be done so that we can be prepared to link in the newer docker client in our product.

Thanks a lot for all the help.

**Comment by jterry75** [comment]
Hey thanks for the query. I can PR up a change today that updates the version number. I will tag this release and publish the changes to nuget. The HTTP version mismatch seems to be a breaking change in .NET Core unfortunately.

**Comment by mrohera** [comment]
Awesome looking forward to it.

**Comment by jterry75** [comment]
Ok the packages (and symbols) have been published. They might take a few to index but you should be good from there. I will document the release so you can have the master version if you need.

**Comment by mrohera** [comment]
We tried this out and looks good. Thank you very much for making the release.
